<?php
$rates = $block->getCurrencyRates();
?>
<table>
    <thead>
        <td>Name</td>
        <td>Code</td>
        <td>Buy</td>
        <td>Transfer</td>
        <td>Sell</td>
    </thead>
    <tbody>
        <?php foreach ($rates as $code => $rate) :?>
            <tr>
                <td><?= $code ?></td>
                <td><?= $rate['name'] ?></td>
                <td><?= $rate['buy'] ?></td>
                <td><?= $rate['transfer'] ?></td>
                <td><?= $rate['sell'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
